-- 3 +/- SELECT COUNT(*) FROM PUBLIC.AUTHORITIES;             
INSERT INTO PUBLIC.AUTHORITIES(ID, AUTHORITY, USUARIO_ID) VALUES
(1, 'USER', 1),
(2, 'USER', 2),
(3, 'ADMIN', 3);

-- 2 +/- SELECT COUNT(*) FROM PUBLIC.RESERVA; 
INSERT INTO PUBLIC.RESERVA(ID, FECHAFINAL, FECHAINICIAL, SALA_ID, USUARIO_ID) VALUES
(1, TIMESTAMP '2018-12-30 12:00:00', TIMESTAMP '2018-12-30 10:00:00', 1, 1),
(2, TIMESTAMP '2018-12-18 20:00:00', TIMESTAMP '2018-12-18 17:30:00', 2, 2);

-- 2 +/- SELECT COUNT(*) FROM PUBLIC.SALA;    
INSERT INTO PUBLIC.SALA(ID, AFOROMAX, NOMBRE) VALUES
(1, 150, 'Biblioteca'),
(2, 300, STRINGDECODE('Sal\u00f3n de actos')); 

-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
INSERT INTO PUBLIC.USUARIO(ID, EMAIL, NOMBRE, NUM_TLF, PASS, VALIDADO) VALUES
(1, 'usuario@usuario.com', 'Usuario', '111222333', '$2a$10$u8MRbcjPah2EGS1znceFy.fTMQ.RWu7xaFfw15ErK2Iz1txV/Ai.u', TRUE),
(2, 'usuario2@usuario2.com', 'Usuario2', '777888999', '$2a$10$flRbaRJhQR2SuosNs6NsquMgfNIRqkMuXJRfdBgsAc3XWMxOTdShy', FALSE),
(3, 'admin@admin.com', 'Admin', '444555666', '$2a$10$kB8XClq0q5fmFzrdvwyqQ.ThDSuw0kQrO5nnLVlyQEJN/8nKzUDEu', TRUE);

ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT PUBLIC.UK_4TDEHXJ7DH8GHFC68KBWBSBLL UNIQUE(EMAIL);  
ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT PUBLIC.UK_5NXBP92JYGM8O49SPMBREVXE1 UNIQUE(NUM_TLF);
ALTER TABLE PUBLIC.AUTHORITIES ADD CONSTRAINT PUBLIC.FK3ODB6UI9OBOYPCY0G7A9V0V3N FOREIGN KEY(USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID) NOCHECK;               
ALTER TABLE PUBLIC.RESERVA ADD CONSTRAINT PUBLIC.FKOHJG86HQ57XFUCUDKQEESG841 FOREIGN KEY(SALA_ID) REFERENCES PUBLIC.SALA(ID) NOCHECK;         
ALTER TABLE PUBLIC.RESERVA ADD CONSTRAINT PUBLIC.FKKRXQWQVEWD2PLS5TDIGWQPRJ2 FOREIGN KEY(USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID) NOCHECK;