DROP SEQUENCE IF EXISTS PUBLIC.SEQ_USUARIO;
DROP SEQUENCE IF EXISTS PUBLIC.SEQ_SALA;
DROP SEQUENCE IF EXISTS PUBLIC.SEQ_RESERVA;
DROP TABLE IF EXISTS PUBLIC.AUTHORITIES;
DROP TABLE IF EXISTS PUBLIC.USUARIO;
DROP TABLE IF EXISTS PUBLIC.RESERVA;
DROP TABLE IF EXISTS PUBLIC.SALA;

;
CREATE USER IF NOT EXISTS SA SALT 'ec84e143ecc50e5b' HASH 'f78351aa065d8562a9c22fb62be894ece5d97b7115b0a3028af87b7b29cfc88e' ADMIN;           
CREATE SEQUENCE PUBLIC.SEQ_USUARIO START WITH 1;              
CREATE SEQUENCE PUBLIC.SEQ_SALA START WITH 1; 
CREATE SEQUENCE PUBLIC.SEQ_RESERVA START WITH 1;              
CREATE CACHED TABLE PUBLIC.AUTHORITIES(
    AUTHORITY VARCHAR(255) NOT NULL,
    EMAIL BIGINT
);           
ALTER TABLE PUBLIC.AUTHORITIES ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(AUTHORITY);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AUTHORITIES;             
CREATE CACHED TABLE PUBLIC.RESERVA(
    ID BIGINT NOT NULL,
    FECHAFINAL TIMESTAMP,
    FECHAINICIAL TIMESTAMP,
    SALA_ID BIGINT,
    USUARIO_ID BIGINT
);          
ALTER TABLE PUBLIC.RESERVA ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESERVA; 
CREATE CACHED TABLE PUBLIC.SALA(
    ID BIGINT NOT NULL,
    AFOROMAX INTEGER NOT NULL,
    NOMBRE VARCHAR(255)
);        
ALTER TABLE PUBLIC.SALA ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SALA;    
CREATE CACHED TABLE PUBLIC.USUARIO(
    ID BIGINT NOT NULL,
    EMAIL VARCHAR(255),
    NOMBRE VARCHAR(255),
    NUMTLF VARCHAR(255),
    PASS VARCHAR(255),
    VALIDADO BOOLEAN NOT NULL
);          
ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT PUBLIC.CONSTRAINT_22 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT PUBLIC.UK_7BVKHIRWL95XJ8QV4PFNTCQP2 UNIQUE(EMAIL);  
ALTER TABLE PUBLIC.AUTHORITIES ADD CONSTRAINT PUBLIC.FK1ENLPXKHYM2T6WMLMM07M5SE8 FOREIGN KEY(EMAIL) REFERENCES PUBLIC.USUARIO(ID) NOCHECK;    
ALTER TABLE PUBLIC.RESERVA ADD CONSTRAINT PUBLIC.FKOHJG86HQ57XFUCUDKQEESG841 FOREIGN KEY(SALA_ID) REFERENCES PUBLIC.SALA(ID) NOCHECK;         
ALTER TABLE PUBLIC.RESERVA ADD CONSTRAINT PUBLIC.FKKRXQWQVEWD2PLS5TDIGWQPRJ2 FOREIGN KEY(USUARIO_ID) REFERENCES PUBLIC.USUARIO(ID) NOCHECK;   
